name: pci
description: Php Continues Integration

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  webui:
    git: http://dev/git/ufds/webui.git
    #path: /home/sb/projects/ufds/webui

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
 - dart_to_js_script_rewriter
 - $dart2js:
    minify: false
